version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      # get source code from Git
      - checkout

      # prepare directory to store test reports
      - run: mkdir -p $TEST_RESULTS

      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "src/go.sum" }}

      - run:
          name: Run unit tests
          working_directory: ./src
          # store the results of our tests in the $TEST_RESULTS directory
          command: |
            PACKAGE_NAMES=$(go list ./... | circleci tests split --split-by=timings --timings-type=classname)
            gotestsum --junitfile ${TEST_RESULTS}/gotestsum-report.xml -- $PACKAGE_NAMES

      - save_cache:
          key: go-mod-v4-{{ checksum "src/go.sum" }}
          paths:
            - "/go/pkg/mod"

      # upload test summary for display in Artifacts
      - store_artifacts:
          path: $TEST_RESULTS
          destination: raw-test-output

      # upload test results for display in Test Summary
      - store_test_results:
          path: $TEST_RESULTS

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
