version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
      - image: circleci/postgres
        environment:
          POSTGRES_USER: estore
          POSTGRES_DB: estore

    steps:
      # get source code from Git
      - checkout

      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "src/go.sum" }}

      #  CircleCi's Go Docker image includes netcat
      #  This allows polling the DB port to confirm it is open before proceeding
      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1

      - run:
          name: Run unit tests
          environment:
            ESTORE_DB_URL: "postgres://estore@localhost:5432/estore?sslmode=disable"

          command: |
            make dbclean test

      - save_cache:
          key: go-mod-v4-{{ checksum "src/go.sum" }}
          paths:
            - "/go/pkg/mod"

      # upload test summary for display in Artifacts
      - store_artifacts:
          path: out/test-reports
          destination: raw-test-output

      # upload test results for display in Test Summary
      - store_test_results:
          path: out/test-reports

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
